name: Build Docker Images and Push to Image Registry

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_ACCESS_NAME }}
          password: ${{ secrets.ALIYUN_ACCESS_PASSWORD }}

      - name: Set up Docker Buildx (optional for multi-platform builds)
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with Makefile
        run: |
          make image-buildx

      - name: Notify success
        run: echo "Docker image built and pushed successfully for tag ${GITHUB_REF#refs/tags/}"


